- hosts: all
  gather_facts: False
  become: yes
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: master
  become: yes
  tasks:




    - name: install docker swarm
      apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
           - apt-transport-https
           - ca-certificates
           - curl
           - software-properties-common
           - python-pip
      state: present
    - name: inst swarm
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && apt-get update && sudo apt-get -y install docker-ce

    - name: add user to docker
      shell: usermod -a -G docker ubuntu
      state: present
    - name: Restart docker
      service:
        name: docker
        state: restarted
    - name: Swarm Init
      command: docker swarm init --advertise-addr {{ inventory_hostname }}
 
   - name: Get Worker Token
     command: docker swarm join-token worker -q
     register: worker_token

   - name: Show Worker Token
     debug: var=worker_token.stdout

   - name: Master Token
     command: docker swarm join-token manager -q
     register: master_token

   - name: Show Master Token
     debug: var=master_token.stdout

- hosts: slave0
  become: yes
  vars:
    token: "{{ hostvars[groups['masters'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['masters'][0]]['inventory_hostname'] }}"
  tasks:    
    - name: install docker swarm
      apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
           - apt-transport-https
           - ca-certificates
           - curl
           - software-properties-common
           - python-pip
      state: present
    - name: inst swarm
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && apt-get update && sudo apt-get -y install docker-ce
    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }} {{ master }}:2377
      register: worker

    - name: Show Results
      debug: var=worker.stdout

    - name: Show Errors
      debug: var=worker.stderr
- hosts: slave1
  become: yes
  vars:
    token: "{{ hostvars[groups['masters'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['masters'][0]]['inventory_hostname'] }}"
  tasks:    
    - name: install docker swarm
      apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
           - apt-transport-https
           - ca-certificates
           - curl
           - software-properties-common
           - python-pip
      state: present
    - name: inst swarm
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && apt-get update && sudo apt-get -y install docker-ce
    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }} {{ master }}:2377
      register: worker

    - name: Show Results
      debug: var=worker.stdout

    - name: Show Errors
      debug: var=worker.stderr
